---
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      # Generall Stuff
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      # VCS
      - id: check-merge-conflict
      # Config / Data Files
      - id: check-yaml
      # Python
      - id: debug-statements
  # Python: flakes8 (syntax check with pyflakes only)
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
      - id: flake8
        args:
          - "--select=F"
  # Python: reorder imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.2.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--application-directories=.:src:tests"
          - "--separate-relative"
  # Python: black
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  # Misc: Prettier (HTML, JS, CSS, Markdown…)
  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier
        exclude: CHANGELOG.md
